const globals = require('globals');
const stylistic = require('@stylistic/eslint-plugin');

module.exports = [
    {
        ignores: ['build/**', 'local/**', 'node_modules/**', '.npm/**', '.npm_cache/**']
    },
    {
        plugins: {
            '@stylistic/js': stylistic
        },
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType: 'commonjs',
            globals: {
                ...globals.node,
                ...globals.browser,
                ...globals.es6
            }
        },
        rules: {
            // Functional Rules
            curly: [2, 'multi-line'],
            'default-case': 2,
            'dot-notation': [2, {allowKeywords: true}],
            eqeqeq: 2,
            'func-names': 2,
            'func-style': [2, 'declaration', {allowArrowFunctions: true}],
            'guard-for-in': 2,
            'no-alert': 2,
            'no-array-constructor': 2,
            'no-bitwise': 2,
            'no-caller': 2,
            'no-class-assign': 2,
            'no-cond-assign': 2,
            'no-console': 0,
            'no-const-assign': 2,
            'no-constant-condition': 1,
            'no-continue': 0,
            'no-control-regex': 2,
            'no-debugger': 2,
            'no-delete-var': 2,
            'no-div-regex': 2,
            'no-dupe-args': 2,
            'no-dupe-class-members': 2,
            'no-dupe-keys': 2,
            'no-duplicate-case': 2,
            'no-else-return': 1,
            'no-empty': 2,
            'no-empty-character-class': 2,
            'no-empty-pattern': 2,
            'no-eq-null': 2,
            'no-eval': 2,
            'no-ex-assign': 2,
            'no-extend-native': 1,
            'no-extra-bind': 2,
            'no-extra-boolean-cast': 2,
            'no-fallthrough': 2,
            'no-func-assign': 2,
            'no-global-assign': 1,
            'no-implicit-coercion': [2, {boolean: false, number: true, string: true}],
            'no-implied-eval': 2,
            'no-inline-comments': 0,
            'no-inner-declarations': [2, 'functions'],
            'no-invalid-regexp': 2,
            'no-invalid-this': 2,
            'no-irregular-whitespace': 2,
            'no-iterator': 2,
            'no-label-var': 2,
            'no-labels': 2,
            'no-lone-blocks': 2,
            'no-lonely-if': 2,
            'no-loop-func': 1,
            'no-magic-numbers': 0,
            'no-mixed-spaces-and-tabs': [2, false],
            'no-multi-str': 2,
            'no-nested-ternary': 0,
            'no-new': 2,
            'no-new-func': 2,
            'no-object-constructor': 2,
            'no-new-wrappers': 2,
            'no-obj-calls': 2,
            'no-octal': 2,
            'no-octal-escape': 2,
            'no-param-reassign': 0,
            'no-plusplus': 2,
            'no-proto': 2,
            'no-redeclare': 2,
            'no-regex-spaces': 2,
            'no-return-assign': 2,
            'no-script-url': 2,
            'no-self-compare': 2,
            'no-sequences': 2,
            'no-shadow': 2,
            'no-shadow-restricted-names': 2,
            'no-sparse-arrays': 2,
            'no-sync': 0,
            'no-ternary': 0,
            'no-this-before-super': 2,
            'no-throw-literal': 1,
            'no-undef': 2,
            'no-undef-init': 2,
            'no-undefined': 0,
            'no-underscore-dangle': 0,
            'no-unexpected-multiline': 2,
            'no-unneeded-ternary': 2,
            'no-unreachable': 2,
            'no-useless-call': 2,
            'no-useless-concat': 2,
            'no-unused-expressions': 2,
            'no-unused-vars': [1, {vars: 'all', args: 'after-used'}],
            'no-use-before-define': 2,
            'no-var': 2,
            'no-void': 2,
            'no-warning-comments': [1, {terms: ['todo', 'fixme', 'xxx'], location: 'start'}],
            'no-unsafe-negation': 2,
            'no-with': 2,
            'object-shorthand': [2, 'always'],
            'one-var': [2, 'never'],
            'operator-assignment': [2, 'always'],
            'prefer-arrow-callback': 2,
            'prefer-const': 1,
            'prefer-spread': 2,
            'prefer-template': 0,
            radix: 2,
            'require-yield': 2,
            strict: [2, 'never'],
            'use-isnan': 2,
            'valid-typeof': 2,
            'vars-on-top': 0,
            yoda: [2, 'never', {exceptRange: true}],

            // Stylistic Rules
            '@stylistic/js/array-bracket-spacing': [2, 'never'],
            '@stylistic/js/arrow-parens': [2, 'as-needed'],
            '@stylistic/js/arrow-spacing': 2,
            '@stylistic/js/brace-style': [2, '1tbs', {allowSingleLine: true}],
            '@stylistic/js/comma-dangle': [2, 'never'],
            '@stylistic/js/comma-spacing': [2, {before: false, after: true}],
            '@stylistic/js/comma-style': [2, 'last'],
            '@stylistic/js/computed-property-spacing': [2, 'never'],
            '@stylistic/js/dot-location': [2, 'property'],
            '@stylistic/js/eol-last': 2,
            '@stylistic/js/generator-star-spacing': [2, 'after'],
            '@stylistic/js/indent': [2, 4, {ignoredNodes: ['TemplateLiteral', 'TemplateLiteral *', 'Literal', 'Literal *']}],
            '@stylistic/js/key-spacing': [2, {beforeColon: false, afterColon: true}],
            '@stylistic/js/keyword-spacing': [2, {before: true, after: true}],
            '@stylistic/js/linebreak-style': [2, 'unix'],
            '@stylistic/js/no-extra-parens': 1,
            '@stylistic/js/no-extra-semi': 2,
            '@stylistic/js/no-floating-decimal': 2,
            '@stylistic/js/no-multi-spaces': 2,
            '@stylistic/js/no-multiple-empty-lines': [2, {max: 4}],
            '@stylistic/js/no-trailing-spaces': 2,
            '@stylistic/js/object-curly-spacing': [2, 'never'],
            '@stylistic/js/operator-linebreak': [2, 'after'],
            '@stylistic/js/padded-blocks': [2, 'never'],
            '@stylistic/js/quote-props': [2, 'as-needed'],
            '@stylistic/js/quotes': [2, 'single', {avoidEscape: true}],
            '@stylistic/js/semi': 2,
            '@stylistic/js/semi-spacing': [2, {before: false, after: true}],
            '@stylistic/js/sort-vars': 0,
            '@stylistic/js/space-before-blocks': [2, 'always'],
            '@stylistic/js/space-before-function-paren': [2, {anonymous: 'always', named: 'never'}],
            '@stylistic/js/space-in-parens': [2, 'never'],
            '@stylistic/js/space-infix-ops': 2,
            '@stylistic/js/space-unary-ops': [2, {words: true, nonwords: false}],
            '@stylistic/js/spaced-comment': [2, 'always'],
            '@stylistic/js/wrap-iife': [2, 'outside'],
            '@stylistic/js/wrap-regex': 2
        }
    },
    {
        files: ['src/**/*.js'],
        rules: {
            'no-console': 1
        }
    },
    // Project uses ES modules for build tooling (gulpfile)
    {
        files: ['gulpfile.js'],
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType: 'module',
            globals: {
                ...globals.node
            }
        },
        rules: {
            'no-undef': 'off'
        }
    }
];
