[PHP]
memory_limit = 512M
max_execution_time = 120
post_max_size = 100M
upload_max_filesize = 100M

; File uploads
file_uploads = On

; Path/directory settings
realpath_cache_size = 4096K
realpath_cache_ttl = 600

; Buffering
output_buffering = 4096
